In [35]:
!pip install lime
import os
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import shap
from lime.lime_tabular import LimeTabularExplainer

warnings.filterwarnings("ignore", category=FutureWarning)
torch.manual_seed(42)
np.random.seed(42)
print("Imports OK")

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lime in /lustre/home/extusers/udlc4dd19/.local/lib/python3.12/site-packages (0.2.0.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from lime) (3.10.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lime) (2.4.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lime) (1.17.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from lime) (4.67.1)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.12/dist-packages (from lime) (1.8.0)
Requirement already satisfied: scikit-image>=0.12 in /lustre/home/extusers/udlc4dd19/.local/lib/python3.12/site-packages (from lime) (0.26.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (3.6.1)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (12.1.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /lustre/home/extusers/udlc4dd19/.local/lib/python3.12/site-packages (from scikit-image>=0.12->lime) (2.38.1)
Requirement already satisfied: tifffile>=2022.8.12 in /lustre/home/extusers/udlc4dd19/.local/lib/python3.12/site-packages (from scikit-image>=0.12->lime) (2026.9.20)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (25.0)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (0.4)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->lime) (1.16.0)
Imports OK

In [36]:
file = pd.read_pickle("dd_all_cycles.pkl")

In [37]:
pd.set_option("display.max_colwidth", None)
print(file.pv.head(10))
len(file)

0    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
1    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp1SDS-DODData
2    HBL-010RFC:RFS-DIG-201:Dwn0-Cmp0SDS-DODData
3    HBL-010RFC:RFS-DIG-201:Dwn0-Cmp1SDS-DODData
4    HBL-010RFC:RFS-DIG-301:Dwn0-Cmp0SDS-DODData
5    HBL-010RFC:RFS-DIG-301:Dwn0-Cmp1SDS-DODData
6    HBL-010RFC:RFS-DIG-401:Dwn0-Cmp0SDS-DODData
7    HBL-010RFC:RFS-DIG-401:Dwn0-Cmp1SDS-DODData
8    HBL-010RFC:RFS-DIG-101:Dwn5-Cmp0SDS-DODData
9    HBL-010RFC:RFS-DIG-101:Dwn5-Cmp1SDS-DODData
Name: pv, dtype: object

218533

In [38]:
test = []

for i in range(len(file)):
    if "HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0" in str(file.iloc[i]["pv"]):
        test.append(file.iloc[i])

test = pd.DataFrame(test)

In [30]:
print(test.pv.head(10))

0      HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
24     HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
48     HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
72     HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
96     HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
120    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
144    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
168    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
192    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
216    HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData
Name: pv, dtype: object

In [51]:
test

,cycle_id,cycle_ts,pv,data_ts,data_array,trig_name,array_dimensions.binning,trig_user_tag,array_dimensions.offset,array_dimensions.reverse,...,source_archive,source_parquet,source_list_line,source_row,data_array_std,data_array_max,data_array_mean,data_array_5000_15000_std,data_array_5000_15000_mean,data_array_5000_15000_ptp
0,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[0.21542916, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.2152958, 0.21536082, 0.21542916, 0.21557578, 0.21565406, 0.21582057, 0.21600029, 0.21629457, 0.21661837, 0.2168506, 0.21709584, 0.21762522, 0.21805611, 0.21851581, 0.21917328, 0.21988122, 0.22083634, 0.221656, 0.2227491, 0.22367771, 0.22515947, 0.22647433, 0.2281464, 0.23022422, 0.23179021, 0.23375729, 0.23617032, 0.23833708, 0.24136305, 0.24413495, 0.24743953, 0.2508844, 0.25400928, 0.25864467, 0.2620043, 0.26695982, 0.27156934, 0.27631316, 0.28173336, 0.2861769, 0.29185835, 0.29767337, 0.30361438, 0.31028625, 0.3164686, 0.32338998, 0.3304302, 0.33758184, 0.34483796, 0.35219213, 0.35963827, 0.36717084, 0.37548062, 0.3838808, 0.39236552, 0.40092942, 0.40956756, 0.419004, 0.42778242, 0.4366219, 0.4462628, 0.45521823, 0.4649771, 0.4740349, 0.48389816, 0.4945754, 0.5045383, 0.5145449, 0.5238184, 0.53467935, 0.5448028, 0.5557437, 0.5667225, 0.57694924, 0.5872052, 0.59828097, 0.6093872, 0.61972594, 0.63088626, 0.6412727, 0.65248185, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,64,7.689251,19.790163,5.557866,7.377371,11.243440,18.428512
24,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[0.21542916, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.2152958, 0.21536082, 0.21542916, 0.21557578, 0.21565406, 0.21582057, 0.21600029, 0.21629457, 0.21661837, 0.2168506, 0.21709584, 0.21762522, 0.21805611, 0.21851581, 0.21917328, 0.21988122, 0.22083634, 0.221656, 0.2227491, 0.22367771, 0.22515947, 0.22647433, 0.2281464, 0.23022422, 0.23179021, 0.23375729, 0.23617032, 0.23833708, 0.24136305, 0.24413495, 0.24743953, 0.2508844, 0.25400928, 0.25864467, 0.2620043, 0.26695982, 0.27156934, 0.27631316, 0.28173336, 0.2861769, 0.29185835, 0.29767337, 0.30361438, 0.31028625, 0.3164686, 0.32338998, 0.3304302, 0.33758184, 0.34483796, 0.35219213, 0.35963827, 0.36717084, 0.37548062, 0.3838808, 0.39236552, 0.40092942, 0.40956756, 0.419004, 0.42778242, 0.4366219, 0.4462628, 0.45521823, 0.4649771, 0.4740349, 0.48389816, 0.4945754, 0.5045383, 0.5145449, 0.5238184, 0.53467935, 0.5448028, 0.5557437, 0.5667225, 0.57694924, 0.5872052, 0.59828097, 0.6093872, 0.61972594, 0.63088626, 0.6412727, 0.65248185, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300_jypcu.tar,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,2,64,7.689251,19.790163,5.557866,7.377371,11.243440,18.428512
48,15643300192,2025-05-29 12:28:20.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:20.838728192+00:00,"[0.2155008, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.21517578, 0.21517578, 0.21523413, 0.2152958, 0.2152958, 0.21542916, 0.2155008, 0.21565406, 0.21573566, 0.21590878, 0.21609509, 0.21629457, 0.21661837, 0.2168506, 0.21722333, 0.21762522, 0.21805611, 0.21851581, 0.21934555, 0.22006603, 0.22083634, 0.22186856, 0.2227491, 0.2239173, 0.22515947, 0.22674593, 0.2281464, 0.23022422, 0.23211145, 0.23409429, 0.23617032, 0.23907909, 0.24175204, 0.24454015, 0.24786259, 0.2508844, 0.25446385, 0.2581723, 0.2620043, 0.26695982, 0.2710504, 0.27631316, 0.28118452, 0.2861769, 0.29185835, 0.29767337, 0.30361438, 0.30967402, 0.3164686, 0.32338998, 0.3304302, 0.33758184, 0.34483796, 0.35219213, 0.35963827, 0.36785972, 0.37548062, 0.3838808, 0.39236552, 0.40092942, 0.40956756, 0.41827536, 0.42704847, 0.43588305, 0.4455189, 0.45521823, 0.4649771, 0.4740349, 0.48389816, 0.49381092, 0.5045383, 0.5137737, 0.5238184, 0.53390217, 0.5448028, 0.5549609, 0.5659371, 0.5761615, 0.58641523, 0.5974888, 0.6077988, 0.6189298, 0.63088626, 0.6412727, 0.6516804, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,56,7.688806,19.790163,5.556844,7.378626,11.241114,18.431036
72,15643300192,2025-05-29 12:28:20.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:20.838728192+00:00,"[0.2155008, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.21517578, 0.21517578, 0.21523413, 0.2152958, 0.2152958, 0.21542916, 0.2155008, 0.21565406, 0.21573566, 0.21590878, 0.21609509, 0.21629457, 0.21661837, 0.2168506, 0.21722333, 0.21762522, 0.21805611, 0.21851581, 0.21934555, 0.22006603, 0.22083634, 0.22186856, 0.2227491, 0.2239173, 0.22515947, 0.22674593, 0.2281464, 0.23022422, 0.23211145, 0.23409429, 0.23617032, 0.23907909, 0.24175204, 0.24454015, 0.24786259, 0.2508844, 0.25446385, 0.2581723, 0.2620043, 0.26695982, 0.2710504, 0.27631316, 0.28118452, 0.2861769, 0.29185835, 0.29767337, 0.30361438, 0.30967402, 0.3164686, 0.32338998, 0.3304302, 0.33758184, 0.34483796, 0.35219213, 0.35963827, 0.36785972, 0.37548062, 0.3838808, 0.39236552, 0.40092942, 0.40956756, 0.41827536, 0.42704847, 0.43588305, 0.4455189, 0.45521823, 0.4649771, 0.4740349, 0.48389816, 0.49381092, 0.5045383, 0.5137737, 0.5238184, 0.53390217, 0.5448028, 0.5549609, 0.5659371, 0.5761615, 0.58641523, 0.5974888, 0.6077988, 0.6189298, 0.63088626, 0.6412727, 0.6516804, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300_jypcu.tar,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,2,56,7.688806,19.790163,5.556844,7.378626,11.241114,18.431036
96,15643300206,2025-05-29 12:28:21.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:21.838728192+00:00,"[0.21542916, 0.21502073, 0.21502073, 0.21502073, 0.21502073, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.21517578, 0.21517578, 0.21523413, 0.2152958, 0.21536082, 0.2155008, 0.21557578, 0.21565406, 0.21582057, 0.21609509, 0.21629457, 0.21650717, 0.21673286, 0.21709584, 0.21762522, 0.21805611, 0.21851581, 0.21917328, 0.22006603, 0.22083634, 0.221656, 0.2227491, 0.22367771, 0.22515947, 0.22674593, 0.2281464, 0.23022422, 0.23211145, 0.23409429, 0.23617032, 0.23870687, 0.24136305, 0.24454015, 0.24786259, 0.2508844, 0.25446385, 0.2581723, 0.2624917, 0.26695982, 0.27156934, 0.27631316, 0.28173336, 0.2861769, 0.29243395, 0.29767337, 0.30481702, 0.31028625, 0.3170927, 0.3240252, 0.3304302, 0.33758184, 0.34483796, 0.35286534, 0.36100158, 0.3685493, 0.37617728, 0.3845847, 0.3930762, 0.4016465, 0.41029063, 0.4197331, 0.42778242, 0.43736118, 0.4462628, 0.45596686, 0.46573013, 0.47554898, 0.48465896, 0.4945754, 0.5045383, 0.51531637, 0.52536726, 0.53467935, 0.54558295, 0.5557437, 0.5667225, 0.57773715, 0.58799523, 0.59828097, 0.6093872, 0.61972594, 0.63088626, 0.64207256, 0.65248185, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,48,7.688516,19.789314,5.556556,7.378644,11.240167,18.430187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216198,16123106098,2026-06-30 04:20:34.055134788+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-PMData,2026-06-30 04:20:34.060934771+00:00,"[0.21474373, 0.21445283, 0.21450436, 0.21455923, 0.21461742, 0.21461742, 0.21474373, 0.21461742, 0.21467891, 0.21467891, 0.21467891, 0.21461742, 0.21455923, 0.21461742, 0.21467891, 0.21474373, 0.21495809, 0.21511751, 0.21557373, 0.2158868, 0.21660091, 0.21714167, 0.21773371, 0.21889198, 0.22020358, 0.22233787, 0.2245143, 0.22692567, 0.22987147, 0.2324232, 0.23444712, 0.23839405, 0.24303365, 0.24843091, 0.25328144, 0.2569635, 0.26173958, 0.26720434, 0.2723534, 0.27983305, 0.287042, 0.29274794, 0.29917538, 0.304545, 0.31062144, 0.31805727, 0.3250028, 0.3333598, 0.34120724, 0.3491737, 0.35522187, 0.36064792, 0.36749327, 0.37509942, 0.38207954, 0.39265913, 0.39906612, 0.40551496, 0.4112808, 0.4178034, 0.42436248, 0.43095636, 0.43537086, 0.44201928, 0.44646877, 0.45093152, 0.45466036, 0.45839792, 0.46439567, 0.4696609, 0.47267663, 0.47796607, 0.4794801, 0.48099527, 0.48402914, 0.48934957, 0.49087223, 0.4946837, 0.49544683, 0.49544683, 0.49544683, 0.49621022, 0.49926645, 0.50156134, 0.5038586, 0.50079614, 0.50232685, 0.50156134, 0.50156134, 0.5053915, 0.5123015, 0.51768976, 0.5254072, 0.530823, 0.53547364, 0.542464, 0.549471, 0.55727535, 0.56823313, 0.5776535, ...]",HBL-010RFC:RFS-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/HBL.parquet,44,160,8.992045,19.959417,10.387749,0.001491,19.951924,0.011002
216695,16123106112,2026-06-30 04:20:35.055134743+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-PMData,2026-06-30 04:20:35.060934726+00:00,"[0.21488333, 0.21450436, 0.21455923, 0.21461742, 0.21467891, 0.21467891, 0.21467891, 0.21461742, 0.21467891, 0.21474373, 0.21467891, 0.21474373, 0.21461742, 0.21461742, 0.21467891, 0.21467891, 0.21488333, 0.21511751, 0.2154759, 0.21577917, 0.21660091, 0.21714167, 0.21758091, 0.21854529, 0.21981335, 0.22123283, 0.22376238, 0.22636989, 0.2286601, 0.23144639, 0.23444712, 0.23839405, 0.24303365, 0.24843091, 0.25283018, 0.25790358, 0.26222742, 0.26669875, 0.2723534, 0.27874598, 0.2853569, 0.29274794, 0.29917538, 0.30394363, 0.3093972, 0.31680748, 0.3250028, 0.3327115, 0.34186667, 0.3491737, 0.35522187, 0.36201152, 0.3681815, 0.37509942, 0.38418522, 0.39194992, 0.4012112, 0.406234, 0.41272703, 0.41853043, 0.42582485, 0.43095636, 0.43758348, 0.44201928, 0.44572625, 0.44944248, 0.4539139, 0.4576497, 0.46514687, 0.4696609, 0.47569734, 0.47645327, 0.47796607, 0.4817533, 0.48327026, 0.48630762, 0.49011075, 0.49392086, 0.4946837, 0.49544683, 0.49544683, 0.49621022, 0.49926645, 0.50156134, 0.50309265, 0.5046249, 0.5046249, 0.5046249, 0.5046249, 0.5084601, 0.5123015, 0.52077395, 0.5261802, 0.53314734, 0.5362495, 0.5416865, 0.54869163, 0.55805683, 0.56980145, 0.579226, ...]",HBL-010RFC:RFS-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/HBL.parquet,44,120,8.991117,19.960264,10.389430,0.001495,19.951958,0.011848
217192,16123106126,2026-06-30 04:20:36.055134698+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-PMData,2026-06-30 04:20:36.060934681+00:00,"[0.21474373, 0.21455923, 0.21455923, 0.21455923, 0.21450436, 0.21450436, 0.21455923, 0.21455923, 0.21450436, 0.21467891, 0.21461742, 0.21461742, 0.21455923, 0.21461742, 0.21467891, 0.21467891, 0.21495809, 0.21511751, 0.21567482, 0.21611184, 0.21660091, 0.21728489, 0.21821117, 0.21907002, 0.22060612, 0.22233787, 0.22503012, 0.22664636, 0.22926034, 0.23176935, 0.23514225, 0.23952201, 0.24343541, 0.24843091, 0.25373474, 0.25790358, 0.2627171, 0.26669875, 0.27183104, 0.2782047, 0.28760648, 0.29390508, 0.30095446, 0.3057512, 0.3118501, 0.31868368, 0.32627827, 0.3346591, 0.34120724, 0.34850547, 0.35319906, 0.35792917, 0.3668057, 0.37440476, 0.38137883, 0.3884121, 0.39692572, 0.40479642, 0.4112808, 0.41489986, 0.42144296, 0.42802158, 0.43389773, 0.43906054, 0.4449841, 0.45018682, 0.452422, 0.45914647, 0.46514687, 0.47041437, 0.4741864, 0.47645327, 0.47796607, 0.4794801, 0.4825116, 0.4870677, 0.48934957, 0.49392086, 0.4946837, 0.49621022, 0.49621022, 0.4977378, 0.50079614, 0.5038586, 0.5046249, 0.5053915, 0.5046249, 0.5046249, 0.5053915, 0.5076926, 0.51460934, 0.52000254, 0.5254072, 0.5292745, 0.53392255, 0.540132, 0.54869163, 0.55883855, 0.56980145, 0.579226, ...]",HBL-010RFC:RFS-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/HBL.parquet,44,80,8.991464,19.960264,10.388864,0.001453,19.951963,0.011002
217689,16123106140,2026-06-30 04:20:37.055134652+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-PMData,2026-06-30 04:20:37.060934635+00:00,"[0.21474373, 0.21450436, 0.21461742, 0.21467891, 0.21461742, 0.21450436, 0.21455923, 0.21467891, 0.21467891, 0.21467891, 0.21461742, 0.21455923, 0.21467891, 0.21467891, 0.21474373, 0.21481188, 0.21488333, 0.21520217, 0.21557373, 0.21611184, 0.21686485, 0.21728489, 0.21804886, 0.21871705, 0.22000691, 0.22256787, 0.22503012, 0.22836411, 0.2304934, 0.23275405, 0.23514225, 0.23952201, 0.24343541, 0.24886139, 0.25283018, 0.25743258, 0.2627171, 0.26771167, 0.2728774, 0.27983305, 0.28817233, 0.2944856, 0.29917538, 0.304545, 0.30878672, 0.3155618, 0.32436648, 0.3327115, 0.34120724, 0.3491737, 0.35454687, 0.35928714, 0.36543253, 0.37371075, 0.38137883, 0.3884121, 0.3955014, 0.40192723, 0.40911502, 0.41417512, 0.42071417, 0.42728892, 0.43389773, 0.43979964, 0.44424233, 0.4479549, 0.452422, 0.45690185, 0.46289423, 0.46890777, 0.4741864, 0.47569734, 0.47796607, 0.4802375, 0.48327026, 0.4870677, 0.49163398, 0.4931583, 0.4946837, 0.49544683, 0.49697387, 0.498502, 0.50079614, 0.50309265, 0.5046249, 0.50232685, 0.5038586, 0.5038586, 0.5046249, 0.5076926, 0.51460934, 0.52000254, 0.52695346, 0.53159755, 0.5362495, 0.540132, 0.5471335, 0.55571294, 0.5674493, 0.5776535, ...]",HBL-010RFC:RFS-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/HBL.parquet,44,40,8.989911,19.961109,10.391645,0.001493,19.951964,0.011003
218186,16123106154,2026-06-30 04:20:38.055134607+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-PMData,2026-06-30 04:20:38.060934590+00:00,"[0.21461742, 0.21445283, 0.21450436, 0.21461742, 0.21495809, 0.21488333, 0.21474373, 0.21488333, 0.21474373, 0.21488333, 0.21474373, 0.21467891, 0.21461742, 0.21461742, 0.21461742, 0.21481188, 0.21488333, 0.21495809, 0.21529013, 0.21611184, 0.21714167, 0.21728489, 0.21821117, 0.21925119, 0.22040331, 0.22233787, 0.22477077, 0.22778039, 0.23018108, 0.23275405, 0.23584749, 0.23876762, 0.24383946, 0.24886139, 0.25464734, 0.2588513, 0.26320857, 0.26873145, 0.27393022, 0.28037885, 0.28817233, 0.2944856, 0.30095446, 0.30635604, 0.3118501, 0.31743184, 0.32436648, 0.3327115, 0.3405486, 0.34850547, 0.35454687, 0.36064792, 0.36749327, 0.37509942, 0.38348272, 0.39124125, 0.39835215, 0.40192723, 0.4069535, 0.41345084, 0.42144296, 0.42728892, 0.4346341, 0.43979964, 0.4449841, 0.44944248, 0.452422, 0.45615435, 0.46064457, 0.46665028, 0.47267663, 0.47569734, 0.47720954, 0.4817533, 0.48327026, 0.48782805, 0.49163398, 0.49544683, 0.49544683, 0.4946837, 0.4946837, 0.49697387, 0.49926645, 0.50232685, 0.5038586, 0.5038586, 0.5038586, 0.50309265, 0.50309265, 0.5053915, 0.5123015, 0.5192314, 0.5261802, 0.53159755, 0.53547364, 0.540132, 0.54869163, 0.55805683, 0.56823313, 0.5768675, ...]",HBL-010RFC:RFS-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/HBL.parquet,44,0,8.991414,19.959417,10.388966,0.001520,19.951933,0.011003

In [39]:
file

,cycle_id,cycle_ts,pv,data_ts,data_array,trig_name,array_dimensions.binning,trig_user_tag,array_dimensions.offset,array_dimensions.reverse,...,source_archive,source_parquet,source_list_line,source_row,data_array_std,data_array_max,data_array_mean,data_array_5000_15000_std,data_array_5000_15000_mean,data_array_5000_15000_ptp
0,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[0.21542916, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21506907, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21512076, 0.21517578, 0.21517578, 0.2152958, 0.21536082, 0.21542916, 0.21557578, 0.21565406, 0.21582057, 0.21600029, 0.21629457, 0.21661837, 0.2168506, 0.21709584, 0.21762522, 0.21805611, 0.21851581, 0.21917328, 0.21988122, 0.22083634, 0.221656, 0.2227491, 0.22367771, 0.22515947, 0.22647433, 0.2281464, 0.23022422, 0.23179021, 0.23375729, 0.23617032, 0.23833708, 0.24136305, 0.24413495, 0.24743953, 0.2508844, 0.25400928, 0.25864467, 0.2620043, 0.26695982, 0.27156934, 0.27631316, 0.28173336, 0.2861769, 0.29185835, 0.29767337, 0.30361438, 0.31028625, 0.3164686, 0.32338998, 0.3304302, 0.33758184, 0.34483796, 0.35219213, 0.35963827, 0.36717084, 0.37548062, 0.3838808, 0.39236552, 0.40092942, 0.40956756, 0.419004, 0.42778242, 0.4366219, 0.4462628, 0.45521823, 0.4649771, 0.4740349, 0.48389816, 0.4945754, 0.5045383, 0.5145449, 0.5238184, 0.53467935, 0.5448028, 0.5557437, 0.5667225, 0.57694924, 0.5872052, 0.59828097, 0.6093872, 0.61972594, 0.63088626, 0.6412727, 0.65248185, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,64,7.689251,19.790163,5.557866,NaN,NaN,NaN
1,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-101:Dwn0-Cmp1SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[15.939585, 89.99326, 89.99326, 89.99326, 44.993134, 44.993134, 44.993134, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 26.563644, 33.68365, 33.68365, 36.865974, 38.656467, 33.68365, 32.005066, 33.68365, 34.98456, 33.68365, 35.530098, 32.90031, 32.27084, 31.753277, 32.005066, 30.648207, 30.962942, 31.21473, 29.578106, 29.291348, 28.067379, 27.47288, 27.402937, 26.94832, 26.563644, 25.899202, 25.339674, 25.12985, 24.14368, 23.56317, 23.262423, 22.807804, 22.402145, 21.877588, 21.415976, 21.143206, 20.63963, 19.982183, 19.583519, 19.226818, 18.61833, 18.247643, 17.737072, 17.191532, 16.932749, 16.471138, 15.974556, 15.582886, 15.163239, 14.771568, 14.414868, 14.079151, 13.764416, 13.435693, 13.169916, 12.883158, 12.610387, 12.211722, 11.973923, 11.757105, 11.386417, 11.1975765, 10.868853, 10.554117, 10.281347, 9.994589, 9.728812, 9.477024, 9.218242, 8.994431, 8.672701, 8.462877, 8.155137, 7.9732895, 7.686531, 7.4137607, 7.2459016, 7.008102, 6.7703023, 6.6234255, 6.4136024, 6.280714, 6.0778847, 5.8750553, ...]",HBL-010RFC:RFS-EVR-101,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,65,18.397422,89.993263,-25.604455,NaN,NaN,NaN
2,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-201:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12046938, 0.12057827, 0.12057827, 0.12057827, 0.12057827, 0.12057827, 0.12069454, 0.12069454, 0.12081817, 0.12081817, 0.120949134, 0.12108741, 0.12123297, 0.1213858, 0.12154585, 0.12188754, 0.12206912, 0.12245358, 0.12265639, 0.12308301, 0.12353738, 0.12427029, 0.12452813, 0.12534167, 0.12621433, 0.12682834, 0.12779681, 0.12882106, 0.1302712, 0.13181496, 0.13303225, 0.13473201, 0.13651638, 0.13838212, 0.14032596, 0.1433812, 0.14550646, 0.14825715, 0.15110712, 0.15405084, 0.15708303, 0.16019869, 0.16404094, 0.16798873, 0.1720348, 0.1768704, 0.1811068, 0.18614802, 0.19054763, 0.19576529, 0.20106749, 0.20644772, 0.21190003, 0.21821257, 0.22380169, 0.2302583, 0.23596369, 0.24254304, 0.24918047, 0.25587142, 0.2634577, 0.2702493, 0.27708292, 0.28481713, 0.2917302, 0.29954717, 0.30740315, 0.31529522, 0.32322073, 0.3311773, 0.3400517, 0.34717503, 0.3561069, 0.36417016, 0.37315473, 0.38216418, 0.39029258, 0.39934477, 0.40750915, 0.41750878, 0.42661807, 0.43574405, 0.44488564, 0.45404193, 0.46321207, 0.4733142, 0.4825108, 0.49264038, 0.502783, ...]",HBL-010RFC:RFS-EVR-201,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,66,6.971671,17.898592,5.032653,NaN,NaN,NaN
3,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-201:Dwn0-Cmp1SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 134.9934, 153.42987, 153.42987, 134.9934, 134.9934, 134.9934, 123.68391, 123.68391, 104.03045, 104.03045, 101.30974, 99.4563, 98.12742, 89.99326, 89.99326, 84.80363, 80.53722, 77.90044, 75.067825, 73.60606, 72.47301, 71.563774, 67.74499, 65.37398, 63.42962, 61.820972, 59.03032, 57.988197, 55.91794, 54.896797, 53.36509, 52.022217, 50.707325, 48.98677, 48.140484, 46.73467, 45.538673, 43.971992, 43.552345, 42.272423, 41.12539, 40.097256, 39.250965, 38.41167, 37.74024, 36.495285, 35.63501, 34.61387, 34.236187, 33.368916, 32.578583, 31.858189, 31.186752, 30.4174, 29.857872, 29.19343, 28.71783, 28.151308, 27.619755, 26.89936, 26.339832, 25.92718, 25.234762, 24.878063, 24.26258, 23.877905, 23.325369, 22.737864, 22.25527, 21.800652, 21.30407, 20.898413, 20.457783, 19.884266, 19.492596, 18.97503, 18.478449, 18.149725, 17.702103, 17.233496, 16.960726, 16.52709, 16.156403, 15.764732, 15.429015, 15.072315, 14.729604, 14.40088, 14.086145, ...]",HBL-010RFC:RFS-EVR-201,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,67,45.643981,153.429871,30.824067,NaN,NaN,NaN
4,15643300178,2025-05-29 12:28:19.832928256+00:00,HBL-010RFC:RFS-DIG-301:Dwn0-Cmp0SDS-DODData,2025-05-29 12:28:19.838728192+00:00,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027125586, 0.0634494, 0.088901564, 0.10911746, 0.12663028, 0.14244051, 0.1570632, 0.17080359, 0.1838596, 0.1963678, 0.20842683, 0.22011054, 0.23287635, 0.2439363, 0.25476247, 0.2666979, 0.27840692, 0.289917, 0.30125093, 0.3111932, 0.32224435, 0.33316725, 0.34397417, 0.35467565, 0.36528102, 0.3769619, 0.38738987, 0.39659706, 0.40689045, 0.41825306, 0.4284174, ...]",HBL-010RFC:RFS-EVR-301,[0],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20250528_2045_20250530_0416_DD_15643300300.tar_bgntn.gz,SDS_Data/20250528_2045_20250530_0416/DD/15643300300/HBL.parquet,1,68,6.951177,17.723980,4.915631,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218528,16123106168,2026-06-30 04:20:39.055134561+00:00,HEBT-010LWU:PBI-BCM-001:PRC-TR1-ArrayDataSDS-PMData,2026-06-30 04:20:39.055134561+00:00,"[0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0061035156, 0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, -0.012207031, -0.0061035156, 0.0, 0.0, 0.0061035156, 0.0, -0.0061035156, 0.0, -0.0061035156, -0.0061035156, -0.0061035156, -0.0061035156, -0.0061035156, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0061035156, 0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0061035156, -0.0061035156, -0.0061035156, 0.0061035156, -0.0061035156, ...]",PBI-BCM05:Ctrl-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/BCM.parquet,44,81,0.339569,5.963135,0.018807,NaN,NaN,NaN
218529,16123106168,2026-06-30 04:20:39.055134561+00:00,HEBT-160LWU:PBI-BCM-001:PRC-TR1-ArrayDataSDS-PMData,2026-06-30 04:20:39.055134561+00:00,"[0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, -0.012207031, -0.0061035156, 0.0, 0.0, 0.0, -0.012207031, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0061035156, -0.0061035156, 0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]",PBI-BCM06:Ctrl-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/BCM.parquet,44,82,0.339061,5.944824,0.018889,NaN,NaN,NaN
218530,16123106168,2026-06-30 04:20:39.055134561+00:00,MBL-010LWU:PBI-BCM-001:PRC-TR1-ArrayDataSDS-PMData,2026-06-30 04:20:39.055134561+00:00,"[-0.012207031, 0.0, 0.0, 0.0, 0.012207031, 0.0061035156, 0.0061035156, 0.0, -0.012207031, 0.0, -0.012207031, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, -0.0061035156, -0.012207031, 0.0, -0.0061035156, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, -0.012207031, -0.0061035156, -0.012207031, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0061035156, 0.0061035156, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.012207031, -0.012207031, ...]",PBI-BCM03:Ctrl-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/BCM.parquet,44,83,0.340177,5.957031,0.018808,NaN,NaN,NaN
218531,16123106168,2026-06-30 04:20:39.055134561+00:00,DmpL-010Drf:PBI-BCM-001:PRC-TR1-ArrayDataSDS-PMData,2026-06-30 04:20:39.055134561+00:00,"[0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.012207031, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, -0.0061035156, -0.0061035156, 0.0061035156, 0.0061035156, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0061035156, 0.012207031, 0.0, 0.0, 0.0061035156, 0.0, -0.0061035156, 0.0061035156, -0.012207031, 0.0, -0.0061035156, -0.0061035156, -0.0061035156, -0.012207031, 0.0061035156, 0.0, -0.012207031, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, -0.012207031, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, -0.0061035156, -0.0061035156, 0.0, -0.0061035156, ...]",PBI-BCM06:Ctrl-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/BCM.parquet,44,144,0.338187,5.950928,0.018792,NaN,NaN,NaN
218532,16123106168,2026-06-30 04:20:39.055134561+00:00,DmpL-040Drf:PBI-BCM-001:PRC-TR1-ArrayDataSDS-PMData,2026-06-30 04:20:39.055134561+00:00,"[-0.0061035156, 0.0, -0.0061035156, -0.0061035156, 0.0, -0.012207031, 0.0, 0.0, -0.012207031, -0.0061035156, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, -0.0061035156, 0.0, 0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0061035156, -0.0061035156, 0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0061035156, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0061035156, -0.0061035156, -0.012207031, 0.0, -0.0061035156, 0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0061035156, 0.0, -0.0061035156, 0.0, 0.0, -0.0061035156, 0.0, 0.0, 0.0, -0.0061035156, 0.0, 0.0, -0.012207031, -0.0061035156, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0061035156, 0.0, -0.0061035156, ...]",PBI-BCM07:Ctrl-EVR-101,[1],0,[0],[False],...,/lustre/work/pdl18409/shared/data/anomaly-detection/raw/SDS_Data_20260629_2226_20260630_0626_DD_16123106164_ktibi.tar,SDS_Data/20260629_2226_20260630_0626/DD/16123106164/BCM.parquet,44,145,0.337367,5.950928,0.018810,NaN,NaN,NaN